# Memory Game using Verilog

## About

This is my mini project on Memory Game.

In this project there are 3 LEDs and 3 push buttons.

The user has to press the correct button pattern.

If the pattern is correct, WIN becomes 1.

If the pattern is wrong, LOSE becomes 1.

## Software Used

- Verilog HDL
- Vivado

## Files

memory_game.v

memory_game_tb.v

output.txt

## Result

The project is simulated successfully.
